---
- hosts: frontend
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: true
  tasks:
  - name: Update Http to latest version
    package:
      name: httpd
      state: present
    notify: restart server
  - name: Start httpd service at boot
    service:
      name: httpd
      state: started
      enabled: yes
    notify: restart server
  - name: Copy configuration file
    copy:
      src: /home/ansible/file1.txt
      dest: /tmp/file3.txt
    notify: restart server
  handlers:
    - name: restart server
      command: 'shutdown -r now'
